### ISSUE TITLE
paper-autogrow-textarea adding space at the bottom for each line?

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/paper-input#128]
http://jsbin.com/vugovo/2/edit?html,output

Why is paper-autogrow-textarea adding space at the bottom for each new line?

**Comment by morethanreal** [comment]
`paper-autogrow-textarea` needs to style the `textarea` with `font:inherit` so the styles match in the mirror used for autosizing and the `textarea`. You should be able to workaround the issue with that property in the meantime.

**Comment by gertcuykens** [comment]
`font:inherit` indeed works for me, thanks

**Comment by davenotik** [comment]
Nice. `font: inherit` on the `paper-autogrow-textarea` made it so much better.

**Comment by diegohaz** [comment]
Nice. It works great for me.

**Comment by gertcuykens** [comment]
And why is this still not fixed in 1.0?

**Comment by notwaldorf** [comment]
@gertcuykens the jsbin doesn't work anymore, and this is before I worked on `paper-textarea`, so I'm not sure what I should look at :)
Would you mind filing a bug for https://github.com/PolymerElements/paper-input with a jsbin using the 1.0 elements, so I can repro it? Thanks!

**Comment by gertcuykens** [comment]
Well I added 2 :P

**Comment by gertcuykens** [comment]
Fixed in paper-textarea 1.0
