### ISSUE TITLE
Don't collapse the error-text height

### ISSUE THREAD

**Issue by mattkrick** [Polymer/paper-input#130]
I suggest putting the 'hidden' attribute on the error-icon instead of error-text. Here's why:
1. When error-text is expanded, EVERYTHING on the page suddenly jumps down including inline spans, and divs sitting peacefully below, minding their own business. This is visible on the demo page.
2. Jumpy text is ugly.
3. The floatingLabel height doesn't collapse, so neither should the error!

Argument against a static-height error-text:
1. It adds a vertical offset to the line height so inline text is misaligned.

Reason why that argument is hogwash:
1. You can add a negative vertical-align to the decorator to counteract the offset. Done!

PR available upon request :-)

**Comment by morethanreal** [comment]
This probably needs to be an option, because there might be times you never want to show the error text (for example if you're not using validation) and you don't want to have the additional space under the element. Please feel free to submit a PR.
