### ISSUE TITLE
paper-autogrow-textarea has problems calculating height on multiple lines

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/paper-input#162]
example 

http://embed.plnkr.co/js3uFQSRsIR7SuGLt2gP/preview

this does not work

t1.value = 'some\ntext';
a1.update();

**Comment by gertcuykens** [comment]
Need expert advice please :) I need this thing working

**Comment by gghez** [comment]
Did you try:
```
this.$.a1.update(this.$.t1);
```

When reading autogrow source code, when update argument is not provided it try evaluate an empty token array.

**Comment by notwaldorf** [comment]
Yeah, @gghez is right; you need to pass the textarea element as a parameter. I've created a PR to update the docs.

**Comment by gertcuykens** [comment]
Ok that worked thanks
