### ISSUE TITLE
charCounter exception in GWT

### ISSUE THREAD

**Issue by Neill83** [Polymer/paper-input#170]
Hi!

I tried to use paper-char-counter in GWT - UiBinder but i got an Exception. It's the same like here:
https://github.com/Polymer/paper-input/issues/159

So I need a function to set the element (not the elementId) after the DOM is fully loaded. Maybe this fix could work:
https://github.com/Polymer/paper-input/pull/164

Thanks for your help!

EDIT:

Here the exception:

```
Uncaught TypeError: Cannot read property 'maxLength' of null paper-char-counter.html:101 Polymer.readypolymer.js:9893 base.makeElementReadypolymer.js:9857 base.createdCallbackElement.java:702 $setInnerHTML_0_g$HTMLPanel.java:82 HTMLPanel_3_g$MyView_BinderImpl.java:227 build_f_HTMLPanel1_0_g$MyView_BinderImpl.java:223 get_f_HTMLPanel1_0_g$MyView_BinderImpl.java:31 createAndBindUi_0_g$MyView_BinderImpl.java:28 createAndBindUi_1_g$MyView.java:108 MyView_1_g$UICore.java:46 onModuleLoad_3_g$eu_00046plentymarkets_00046uicore_00046UICore__EntryMethodHolder.java:3 init_2_g$ModuleUtils.java:44 initializeModules_0_g$Impl.java:247 apply_0_g$Impl.java:306 entry0_0_g$Impl.java:72 (anonymous function)ModuleUtils.java:55 gwtOnLoad_0_g$Map.java:29 (anonymous function)
```

**Comment by gghez** [comment]
Hi @Neill83 sure it works;) I'm using it today in a paper-input fork.

**Comment by Neill83** [comment]
Hi @gghez ,

ok, i will try using a paper-input instead of a native html input.

**Comment by Neill83** [comment]
@gghez I'm not able to get it working... maybe you can paste me a sample-code using paper-input? I'll appreciate a lot.
Here is my sample code I'm using (with html input).

```html
<paper-input-decorator label="this is a placeholder" layout="" vertical="">
    <input id="input1" is="core-input" maxlength="5"/>
    <paper-char-counter target="input1" class="counter" />
</paper-input-decorator>
``` 

It's a copy of the polymer demo site...

Thanks

**Comment by gghez** [comment]
`<paper-char-counter target="{{ $.input1}}"></paper-char-counter>`

**Comment by Neill83** [comment]
I got it in a different way...

Here the XML:

```html
<paper-input-decorator label="this is a placeholder" layout="" vertical="" error="This is a custom error message">
        <input ui:field="input" is="core-input" maxlength="5"/>
        <paper-char-counter ui:field="charCounterInput" class="counter" />
</paper-input-decorator>
```

Than I had to create a class for the CharCounter like

```java
@JsType
public interface PaperCharCounter extends HTMLElement
{
	void ready();
	@JsProperty
	void setTarget(String id);
}
```

And than I had to set an ID to the input field like

```java
this.input.setId(HTMLPanel.createUniqueId());
```

And than i could set the target to the char counter and calling ready again (in a ScheduledCommand)

```java
Scheduler.get().scheduleDeferred(new Scheduler.ScheduledCommand() {
			@Override
			public void execute()
			{
				charCounterInput.setTarget(input.getId());
				charCounterInput.ready();
			}
		});
```

**Comment by gghez** [comment]
Javascript ES6 code?

**Comment by Neill83** [comment]
Nope, GWT using ui-binder for xml and java classes (see edited comment above)
