### ISSUE TITLE
No cursor in firefox

### ISSUE THREAD

**Issue by losogudok** [Polymer/paper-input#184]
![2015-07-20 20 39 10](https://cloud.githubusercontent.com/assets/5457415/8782637/7b7fe3fa-2f1f-11e5-99b5-7d656fbad330.png)

**Comment by webloem** [comment]
I have the same problem. Running Ubuntu 15.04 with Firefox 39.0. Problem occurs is only in firefox. I noticed the same problem a couple of months ago, so it exists for a while.

**Comment by juliomelo** [comment]
Duplicates PolymerElements/paper-input#110
