### ISSUE TITLE
prevent-invalid-input and allowed-pattern don't do anything

### ISSUE THREAD

**Issue by CSEMike** [Polymer/paper-input#190]
I'm trying to use these fields, but no incantation seems to actually restrict input.

I've tried:

```
   <paper-input label="validation test one" auto-validate pattern="[a-zA-Z]*" error-message="Bad"></paper-input>
   <paper-input label="validation test two" prevent-invalid-input allowed-pattern="[a-zA-Z]*"></paper-input>
   <paper-input label="validation test three" preventInvalidInput allowedPattern="[a-zA-Z]*"></paper-input>
```

The docs are a bit ambiguous about whether or not camelCase is required, so I just tried both. Neither validation test two nor three work. The first one does, lifted directly from the example, suggesting the regexp is okay.

How is one supposed to use prevent-invalid-input? An example would be helpful.

**Comment by notwaldorf** [comment]
I think the regex is wrong (it's not exactly a regex, it's a pattern). This should work: `<paper-input label="only digits" allowed-pattern="[a-zA-Z]" prevent-invalid-input></paper-input>`
