### ISSUE TITLE
When trying to focus an input as a result of a selection action, the keyboard dissapears on android mobile.

### ISSUE THREAD

**Issue by ghost** [Polymer/paper-input#197]
I could reproduce this issue on jsfiddle using google nexus 5. On iphone 6, the input doesn't even show. On desktop, it works fine.
https://jsfiddle.net/simona_butnaru/xt9oxg66/ 

I think the problem is the blur event that is triggered when an item is selected from paper-menu-button.

**Comment by notwaldorf** [comment]
This issue was moved to PolymerElements/paper-input#336
