### ISSUE TITLE
None of the inputs work on iOS 7.x

### ISSUE THREAD

**Issue by robdodson** [Polymer/paper-input#20]
Tested here:
http://www.polymer-project.org/components/paper-input/demo.html

in iOS 7.1.1 with an iPhone can focus into an input (though this can also be flaky) and see the focus animation. Keyboard comes up, but typing never shows up in the input.

On the emulator, the inputs work so this is an issue on real devices only.

**Comment by code2be** [comment]
@morethanreal Even if vulcanized ?

**Comment by f-prime** [comment]
Has this issue been resolved? The issue is closed, but I am still getting this issue. Even when vulcanized.

**Comment by notwaldorf** [comment]
This is a deprecated element that is no longer being maintained. You should consider updating to Polymer 1.0 :)
