### ISSUE TITLE
paper-input fires change event twice

### ISSUE THREAD

**Issue by frankiefu** [Polymer/paper-input#33]
jsinb: http://jsbin.com/hiyiguxi/1/embed?live,html,console

You will see 2 change events in the console for a single change.

**Comment by mlimper** [comment]
I'm having this issue with both, Chrome and Firefox.
It occurs if I use the on-input event to get updates on typing.

BTW, I tried to workaround by using "oninput" instead "on-input", but then I get a JS error. Dunno what that means, but I'm also not very familiar with polymer.
