### ISSUE TITLE
paper inputs conflict with vimium Chrome plugin

### ISSUE THREAD

**Issue by lpappone** [Polymer/paper-input#50]
When using paper inputs in Chrome with Vimium installed (default settings), typing in the input field produces strange behavior.  E.g., attempting to type 'r' reloads the page, attempting to type 't' opens a new tab.  This renders the paper inputs virtually useless for anyone using Chrome and Vimium.  

This behavior is evident on Polymer's own paper inputs "demo" page.

**Comment by fawind** [comment]
Is there a fix for this problem? I am using Vimium 1.49 and I have the same issues.
