### ISSUE TITLE
Date input format and label placeholder collision

### ISSUE THREAD

**Issue by nomego** [Polymer/paper-input#65]
Using the following markup:

```
<paper-input placeholder="Start period" type="date"></paper-input>
```

The placeholder "Start period" and the date placeholders ("mm/dd/yyyy") gets printed on top of each other.
This applies regardless if it's a floatingLabel or not.

The opposite is true when it comes to core-input, the placeholder label is not printed at all: https://github.com/Polymer/core-input/issues/36

I would suggest the same behavior for paper-input as described in the core-input issue.

For paper-inputs with floatingLabels, I would suggest making the label float even when no date is specified.

**Comment by pierreprinetti** [comment]
Currently `alwaysFloatLabel`
